import { ArrowUpRight, Building2, Car, Store } from "lucide-react";

const cases=[
  {icon:Car,tag:"Automotivo",title:"Operação comercial em um só painel",text:"Demonstração de gestão integrada de estoque, leads, anúncios e vendas para concessionárias.",metric:"Mais agilidade",accent:"blue"},
  {icon:Building2,tag:"Imobiliário",title:"Imóveis e oportunidades conectados",text:"Exemplo de uma plataforma que aproxima imóveis, clientes e corretores durante toda a jornada.",metric:"Visão centralizada",accent:"violet"},
  {icon:Store,tag:"Comércio",title:"Estoque, vendas e indicadores",text:"Conceito de sistema para acompanhar produtos, pedidos, clientes e desempenho em tempo real.",metric:"Decisões melhores",accent:"cyan"},
];

export function Cases(){return <section id="cases" className="light-section py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="reveal flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="eyebrow">Aplicações na prática</span><h2 className="section-title mt-5 max-w-3xl text-slate-950">Soluções pensadas para <span className="text-gradient">problemas reais.</span></h2></div><p className="max-w-md text-sm leading-6 text-slate-600">Cenários demonstrativos para visualizar como a tecnologia pode transformar diferentes operações.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{cases.map(({icon:Icon,tag,title,text,metric,accent},i)=><article key={title} className={`case-card case-${accent} reveal group`} style={{transitionDelay:`${i*80}ms`}}><div className="case-top"><span><Icon className="h-5 w-5"/>{tag}</span><ArrowUpRight className="h-5 w-5 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1"/></div><div className="case-screen" aria-hidden><div className="case-sidebar"><i/><i/><i/><i/></div><div className="case-content"><div className="case-metrics"><i/><i/><i/></div><div className="case-graph"><span/><span/><span/><span/><span/><span/></div></div></div><p className="mt-6 text-xs font-semibold uppercase tracking-[.18em] text-blue-600">{metric}</p><h3 className="mt-2 font-display text-2xl font-bold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p><span className="mt-5 inline-block text-xs text-slate-400">Projeto conceitual demonstrativo</span></article>)}</div></div></section>}
