import { useState } from "react";
import { BarChart3, Bell, Boxes, CircleDollarSign, LayoutDashboard, Package, Settings, ShoppingBag, Users } from "lucide-react";

const menu = [[LayoutDashboard,"Dashboard"],[ShoppingBag,"Vendas"],[Users,"Clientes"],[Package,"Produtos"],[CircleDollarSign,"Financeiro"],[BarChart3,"Relatórios"],[Settings,"Configurações"]] as const;
const views = {
  Dashboard: { title:"Visão geral", stats:[["Vendas","R$ 48.650","+12%"],["Clientes","1.248","+8%"],["Pedidos","324","+15%"],["Ticket médio","R$ 149,90","+5%"]], line:"Vendas nos últimos 30 dias" },
  Vendas: { title:"Gestão de vendas", stats:[["Receita","R$ 76.420","+18%"],["Conversão","18,4%","+3%"],["Propostas","86","+11%"],["Meta mensal","82%","no prazo"]], line:"Evolução das vendas" },
  Clientes: { title:"Relacionamento", stats:[["Clientes ativos","1.248","+8%"],["Novos leads","142","+21%"],["Retenção","94%","+2%"],["Atendimentos","38","hoje"]], line:"Crescimento da base" },
  Produtos: { title:"Produtos e estoque", stats:[["Produtos","864","ativos"],["Estoque baixo","12","atenção"],["Categorias","28","organizadas"],["Giro médio","32 dias","-4 dias"]], line:"Movimentação de estoque" },
  Financeiro: { title:"Controle financeiro", stats:[["Recebimentos","R$ 91.300","+9%"],["Pendências","R$ 8.450","-6%"],["Fluxo líquido","R$ 42.180","positivo"],["Previsão","R$ 103 mil","próximo mês"]], line:"Fluxo de caixa" },
  Relatórios: { title:"Indicadores", stats:[["Relatórios","24","disponíveis"],["Automações","18","ativas"],["Exportações","62","este mês"],["Atualização","Tempo real","online"]], line:"Desempenho consolidado" },
  Configurações: { title:"Ambiente do sistema", stats:[["Usuários","32","ativos"],["Integrações","8","conectadas"],["Permissões","6","perfis"],["Disponibilidade","99,9%","estável"]], line:"Atividade do ambiente" },
} as const;
const benefits=[["Gestão centralizada","Tudo que importa em um único ambiente."],["Dados em tempo real","Indicadores claros para decisões melhores."],["Automação","Reduza tarefas repetitivas e ganhe produtividade."],["Integrações","Conecte as ferramentas utilizadas pela empresa."],["Acesso em qualquer lugar","Desktop, tablet e smartphone."]];

export function Platform(){
  const [active,setActive]=useState<keyof typeof views>("Dashboard");
  const view=views[active];
  return <section id="sistemas" className="relative overflow-hidden py-24 sm:py-32"><div className="orb orb-three"/><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="max-w-3xl reveal"><span className="eyebrow">Demonstração interativa</span><h2 className="section-title mt-5">Menos processos manuais.<br/><span className="text-gradient">Mais inteligência</span> para o seu negócio.</h2><p className="mt-5 max-w-2xl text-muted-foreground">Explore as áreas do sistema e veja como as informações mais importantes ficam organizadas em um só lugar.</p></div><div className="mt-16 grid items-start gap-12 lg:grid-cols-[1.35fr_.65fr]"><Dashboard active={active} setActive={setActive} view={view}/><div className="space-y-5 lg:pt-10">{benefits.map(([title,text],i)=><article key={title} className="benefit reveal" style={{transitionDelay:`${i*70}ms`}}><span>0{i+1}</span><div><h3 className="font-display text-lg font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></article>)}</div></div></div></section>
}

function Dashboard({active,setActive,view}:{active:keyof typeof views;setActive:(v:keyof typeof views)=>void;view:(typeof views)[keyof typeof views]}){
  return <div className="dashboard-shell reveal sticky top-28"><aside><div className="flex items-center gap-2 px-3 py-3"><span className="brand-mark brand-mark-small"><i/><i/></span><b className="font-display text-xs tracking-wider">VEXTTY</b></div><div className="mt-4 space-y-1">{menu.map(([Icon,label])=><button type="button" key={label} onClick={()=>setActive(label)} className={`dash-menu w-full text-left ${active===label?"active":""}`} aria-pressed={active===label}><Icon className="h-4 w-4"/><span>{label}</span></button>)}</div></aside><main><header className="flex items-center justify-between"><div><p className="text-xs text-slate-400">{view.title}</p><h3 className="font-display font-semibold">Olá, João!</h3></div><div className="flex items-center gap-2"><button aria-label="Notificações" className="dash-icon"><Bell className="h-4 w-4"/></button><div className="h-8 w-8 rounded-full bg-gradient-to-br from-primary to-violet-500"/></div></header><div className="mt-5 grid grid-cols-2 gap-3 xl:grid-cols-4">{view.stats.map(([a,b,c])=><div key={a} className="dash-stat"><p>{a}</p><strong>{b}</strong><span>{c}</span></div>)}</div><div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_.55fr]"><div className="dash-panel"><div className="flex items-center justify-between"><b>{view.line}</b><small>Tempo real</small></div><div className="dashboard-chart"><svg viewBox="0 0 520 180" preserveAspectRatio="none" aria-label={`Gráfico: ${view.line}`}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0787ff" stopOpacity=".45"/><stop offset="1" stopColor="#0787ff" stopOpacity="0"/></linearGradient></defs><path d="M0 155 C55 150 70 130 115 136 S180 92 220 108 S288 85 320 72 S380 90 410 50 S468 62 520 18 L520 180 L0 180Z" fill="url(#area)"/><path d="M0 155 C55 150 70 130 115 136 S180 92 220 108 S288 85 320 72 S380 90 410 50 S468 62 520 18" fill="none" stroke="#179cff" strokeWidth="4"/></svg></div></div><div className="dash-panel"><b>Origem das vendas</b><div className="donut mx-auto mt-5"><span>62%<small>Digital</small></span></div><div className="mt-5 space-y-2 text-[10px] text-slate-400"><p>● Site <b className="float-right text-white">24%</b></p><p>● WhatsApp <b className="float-right text-white">14%</b></p></div></div></div></main></div>
}
